version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm install
      - run: npm run generate
      - run: git config --global user.email "hmhm903m@gmail.com"
      - run: git config --global user.name "hama1080"
      - run: git clone $DEPLOY_URL deploy
      - run: cp -a dist/. deploy/.
      - run: cd deploy && git commit -am "Auto deploy by CircleCI"
      - run: cd deploy && git push origin master
