version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "91:ba:63:33:85:51:2a:a3:6f:34:a5:c9:a2:57:98:d3"
      - run: npm install
      - run: npm run generate
      - run: git config --global user.email "hmhm903m@gmail.com"
      - run: git config --global user.name "hama1080"
      - run: git clone $DEPLOY_URL out
      - run: cp -a dist/. out/.
      - run: cd out && git status
      - run: cd out && git add -A
      - run: cd out && git commit -m "Auto deploy by CircleCI"
      - run: cd out && git push origin master
